//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxRankTheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciListesi
    {
        public int Id { get; set; }
        public string Adisoyadi { get; set; }
        public string CepTelefonu { get; set; }
        public string Email { get; set; }
    }
}
