//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxRankTheme.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaxRankThemeEntities : DbContext
    {
        public MaxRankThemeEntities()
            : base("name=MaxRankThemeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlgHaber> BlgHaber { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<KullaniciListesi> KullaniciListesi { get; set; }
        public virtual DbSet<Referans> Referans { get; set; }
        public virtual DbSet<Sayfa> Sayfa { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
    }
}
