//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxRankTheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye
    {
        public int Id { get; set; }
        public string AdiSoyadi { get; set; }
        public string EMail { get; set; }
        public string Sifre { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int Durumu { get; set; }
        public int Turu { get; set; }
    }
}
